[tool.poetry]
name = "cronjobs"
version = "0.0.1"
description = ""
authors = ["Lucas Rangel Cezimbra <lucas@cezimbra.tec.br>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
agilize = "^0.0.10"
bancointer = "^0.0.9"
cattrs = "^23.1.2"
oauth2client = "^4.1.3"
loguru = "^0.7.2"
pygsheets = "^2.0.6"
pyitau = "^1.3.0"
pynubank = "^2.25.0"
pypdf2 = "^3.0.1"
python-decouple = "^3.8"


[tool.poetry.group.dev.dependencies]
coveralls = "^3.3.1"
faker = "^20.0.0"
pre-commit = "^3.4.0"
pytest = "^7.4.2"
pytest-cov = "^4.1.0"
pytest-mock = "^3.11.1"

[tool.ruff]
select = ["E", "F", "I"]
ignore = ["E501"]
line-length = 88



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
